version: '3.8'
services:  
    db:
      container_name: mysql-nodejs
      image: mysql:5.7.35
      #restart: always
      environment:
        MYSQL_USER: micronode
        MYSQL_PASSWORD: micronode
        MYSQL_ROOT_PASSWORD: root1234
        MYSQL_DATABASE: micronodeapi
      ports:
      - "3306:3306"
      # volumes:
      # - ./mysql-data:/var/lib/mysql